id: 2d0c7659-1227-4266-a36b-ca768fe78008
title: Durability (10x)
subtitle:
description:
version: 1.1.2
category: 5
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  -  { name: 'Jjiinx', link: 'https://gamebanana.com/members/1660529' }
