id: cedb2649-774f-4ed1-94f8-092db4357a32
title: Lazy Pack Generator
subtitle: Lazy Pack Python script.
description: Combination of over a dozen patches, now simpler than ever.
version: 4.2.0
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Patchanon, OldManKain, theboy181, Sweetmini, MaxLastBreath, StevenssND' }