id: 09631ff6-24c5-4eee-9b1a-754ad5eb81d1
title: Chuck's 1080p
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

