id: a01bad8d-ff1e-4737-b1e4-dd002bc881e1
title: Swimming Speed (2x)
subtitle:
description:
version: 1.2.1
category: 5
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.1
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
  -  { name: 'Father Of Egg', link: }

