id: f7240190-ebfa-4eda-8406-6c532accbf27
title: Shadows - 256x - performance boost
subtitle:
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

