id: bfdbdc2a-189e-43d4-ae0b-bcc662f0d93d
title: Sweetmini 1008p
subtitle: FXAA On - Includes FSR and DynRes Disabler
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - 0ef8f231-8d97-486e-bfa1-e40f578eed9d
    - d356a7a2-4e8f-4187-8321-7f4d56d1a2f6
author: 
  - { name: Sweetmini, link: }

