id: 9fd109e8-b968-497e-8de8-ab45656da9ba
title: Disable Internal FXAA v2
subtitle:
description:
version: 2.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: Sweetmini, link: }
