id: 616ba43c-cda1-412c-8593-13949feaf315
title: Chuck's 1008p
subtitle:
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: 'ChucksFeedAndSeed, MaxLastBreath', link: https://www.reddit.com/user/ChucksFeedAndSeed/ }

