id: 05fee1ba-09ab-4c9e-a660-b6ccff787931
title: Lazy Pack - 60 FPS - 4K 2X - 8K 4X - UI Mod Compatible
subtitle: 'it just werks'
description: Combination of over a dozen patches. Compatible with most mods. This one is compatible with your controller mod.
version: 3
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, ChanseyIsTheBest, OldManKain, Sweetmini' }
    