id: 40cf707c-e5fe-4722-a5ee-4930f0a95a92
title: Lazy Pack - 30 FPS - 720p 1X - UI Mod Compatible
subtitle: 'it just werks'
description: Combination of over a dozen patches. Compatible with most mods. This one is compatible with your controller mod.
version: 3
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, bad1dea, OldManKain, Sweetmini, MaxLastBreath' }
    