id: d47bd933-c709-4d8d-87dd-5ff85f073978
title: Linux Pack Generator
subtitle: Lazy Pack Python script for linux.
description: Combination of over a dozen patches, now simpler than ever.
version: 4.2.0
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Patchanon, OldManKain, theboy181, Sweetmini, MaxLastBreath, StevenssND' }