id: 56d955c5-81d4-40d5-8061-4b9f9fb47459
title: DynamicFPS v1.5.3
subtitle: Use with standalone fps mods only
description:
version: 1.5.3
category: 1
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  blacklist:
    - 771f46a1-7593-4f67-832e-69839978f559
    - 006614d4-5626-4779-893f-0d06f4420a9e
author:
  - { name: ChucksFeedAndSeed, link: https://www.reddit.com/user/ChucksFeedAndSeed/ }
