id: 896463ab-dcd9-4810-b08c-f52d623f44a5
title: Lazy Pack - 60 FPS - 720p 1X
subtitle: 'it just werks'
description: Combination of over a dozen patches. Compatible with most mods. This one is compatible with your controller mod.
version: 3.0.0
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, bad1dea, OldManKain, Sweetmini, MaxLastBreath, StevenssND' }
    