id: 7f83659e-2e3d-449e-9a6f-dbff26435c15
title: DynamicFPS - 3840x2160 resolution (disable other resolution mods, set emu to 1x scale and enable 'Unsafe extended memory layout (8GB DRAM)')
subtitle: Use with DynamicFPS - v1.5.5 or higher
description: Configuration file for newer DynamicFPS. Configure the .ini file with the desired resolution.
version: 1.0.0
category: 1
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - 624c62b4-c142-47a5-a0c7-9144798e812a
    - 43b13035-3afc-4796-ad89-175199527e1b
    - 25cafd04-3ebc-432c-bc61-fedddfe251ca
author:
  - { name: ChucksFeedAndSeed, link: https://www.reddit.com/user/ChucksFeedAndSeed/ }
