id: 4948a8de-938f-48eb-86b1-c19813fdbb60
title: 540p - Cheat Method - Use 2X Scaling for 1080p
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

