id: bb4173bc-ea4d-4901-86ca-693d55f64de2
title: Lazy Pack - 60 FPS - 720P 1X - 1440P 2X - 4K 3X - 8K 6X
subtitle: Lazy Pack - 60 FPS - 4K 2X - 8K 4X
description: Combination of over a dozen patches. Compatible with most mods. Use UI Mod Compatible version if you want to use a controller mod such as Playstation UI.
version: 3
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, bad1dea, OldManKain, Sweetmini, MaxLastBreath' }
    