id: 2f3a4fc0-cba2-480d-a427-0bba8c1b9507
title: 1026p
subtitle: FXAA On - Disables FSR filter and scaler, and DynRes
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author: { name: 'Zeikken, Socats, Darktalon' }

